# vim:ft=ruby

tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/services'
tap 'theseal/ssh-askpass'

brew 'antigen'
brew 'bat'
brew 'chruby'
brew 'coreutils'
brew 'elixir'
brew 'exa'
brew 'ghc'
brew 'git'
brew 'jq'
brew 'moreutils'
brew 'neovim'
brew 'python'
brew 'rename'
brew 'ruby-install'
brew 'rust'
brew 'ssh-askpass'
brew 'the_silver_searcher'
brew 'trash'
brew 'zsh-syntax-highlighting'

# for ruby
brew 'gdbm'
brew 'libffi'
brew 'libyaml'
brew 'openssl'
brew 'readline'

cask 'alfred'
cask 'dropbox'
cask 'font-fira-code'
cask 'iterm2'
cask 'java8'
cask 'textexpander'
cask 'vimr'

case `hostname -s`
when 'benjamins-macbook-pro'
  brew 'get_iplayer'
  brew 'npm'
  cask 'adobe-acrobat-reader'
  cask 'calibre'
  cask 'foxitreader'
  cask 'papers'
  cask 'skype'
  cask 'steam'
  cask 'transmission'
  cask 'vlc'
when 'c02x937zjg5l'
  brew 'awscli'
  brew 'docker-compose'
  brew 'gsl'
  brew 'libmagic'
  brew 'proj'
  brew 's3cmd'
  brew 'terraform'
  cask 'chromedriver'
  cask 'google-chrome'
end
