# -*- ruby -*-

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'

brew 'chruby'
brew 'colordiff'
brew 'coreutils'
brew 'get_iplayer'
brew 'jq'
brew 'mercurial'
brew 'moreutils'
brew 'ncdu'
brew 'neovim'
brew 'rename'
brew 'ruby-install'
brew 'sleepwatcher', restart_service: true
brew 'srm'
brew 'the_silver_searcher'
brew 'trash'
brew 'tree'
brew 'zsh-syntax-highlighting'

# for ruby
brew 'gdbm'
brew 'libffi'
brew 'libyaml'
brew 'openssl'
brew 'readline'

cask 'adobe-acrobat-reader'
cask 'alfred'
cask 'calibre'
cask 'dropbox'
cask 'foxitreader'
cask 'iterm2'
cask 'java'
cask 'papers'
cask 'skype'
cask 'steam'
cask 'sublime-text'
cask 'transmission'
cask 'vlc'
