# vim:ft=ruby

tap 'homebrew/bundle'
tap 'homebrew/cask'

brew 'bat'
brew 'chruby'
brew 'colordiff'
brew 'coreutils'
brew 'editorconfig'
brew 'get_iplayer'
brew 'git'
brew 'jq'
brew 'mercurial'
brew 'moreutils'
brew 'ncdu'
brew 'neovim'
brew 'npm'
brew 'rename'
brew 'ruby-install'
brew 'srm'
brew 'the_silver_searcher'
brew 'trash'
brew 'tree'
brew 'zsh-syntax-highlighting'

# for ruby
brew 'gdbm'
brew 'libffi'
brew 'libyaml'
brew 'openssl'
brew 'readline'

cask 'adobe-acrobat-reader'
cask 'alfred'
cask 'calibre'
cask 'dropbox'
cask 'foxitreader'
cask 'iterm2'
cask 'java'
cask 'papers'
cask 'skype'
cask 'steam'
cask 'transmission'
cask 'vimr'
cask 'vlc'
