Style/AsciiComments:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/LineLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
