tap "alphagov/gds"

brew "alphagov/gds/gds-cli"
brew "alphagov/gds/govuk-connect"
brew "dnsmasq"
brew "gnupg"
brew "mysql"
brew "pinentry"
brew "pv"
brew "terraform-docs"
brew "tfenv"

cask "1password"
cask "aws-vault"
cask "docker"
cask "gpg-suite"
