source 'https://rubygems.org'

gem 'git-up'
gem 'pry'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'

group :chef do
  gem 'berkshelf'
  gem 'chef'
  gem 'chefspec'
  gem 'fauxhai'
  gem 'foodcritic'
  gem 'kitchen-vagrant'
  gem 'serverspec'
  gem 'test-kitchen'
end
