[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4", "-p"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettierd', args = ["dummy.css"] }

[[language]]
name = "scss"
formatter = { command = 'prettierd', args = ["dummy.scss"] }

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "go"
config = { gopls = { gofumpt = true } }

[[language]]
name = "html"
formatter = { command = 'prettierd', args = ["dummy.html"] }

[[language]]
name = "javascript"
auto-format = true
language-server = { command = "rome", args = ["lsp-proxy"] }
formatter = { command = "rome", args = [
  "format",
  "--stdin-file-path",
  "test.js",
] }

[[language]]
name = "json"
auto-format = true
formatter = { command = "rome", args = [
  "format",
  "--stdin-file-path",
  "test.json",
] }

[[language]]
name = "lua"
auto-format = true
formatter = { command = "stylua", args = [
  "--config-path",
  "/Users/ben/.config/stylua/stylua.toml",
  "--stdin-filepath",
  "dummy.lua",
  "-",
] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = 'prettierd', args = ["dummy.md"] }

[[language]]
name = "python"
auto-format = true
config = { pylsp = { plugins = { black = { enabled = true }, ruff = { enabled = true } } } }

[[language]]
name = "ruby"
auto-format = true
language-server = { command = "standardrb", args = ["--lsp"] }

[[language]]
name = "rust"
formatter = { command = "cargo", args = [
  "clippy",
  "--fix",
  "--allow-dirty",
  "--allow-staged",
] }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "rome", args = [
  "format",
  "--stdin-file-path",
  "test.ts",
] }

[[language]]
name = "yaml"
formatter = { command = 'prettierd', args = ["dummy.yaml"] }
auto-format = true
