[[language]]
name = "bash"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = 'shfmt', args = ["-i", "0", "-ln=bash", "-s"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettierd', args = ["dummy.css"] }

[[language]]
name = "scss"
formatter = { command = 'prettierd', args = ["dummy.scss"] }

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint"]

[[language]]
name = "gotmpl"
language-servers = ["gopls"]
formatter = { command = 'sh', args = [
  "-c",
  "sed -E 's,\\{\\{,{%,g;s,}},%},g' | djlint --custom-blocks define,range,with --reformat --quiet - | sed -E 's,\\{%,{{,g;s,%},}},g'",
] }
auto-format = true

[[language]]
name = "html"
formatter = { command = 'djlint', args = [
  "--reformat",
  "--indent",
  "2",
  "--format-js",
  "--format-css",
  "--quiet",
  "-",
] }

[[language]]
name = "ini"
file-types = [{ suffix = "aws/config" }, { suffix = "aws/credentials" }]

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server", "biome"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.js"] }

[[language]]
name = "json"
language-servers = ["vscode-json-language-server", "biome"]
formatter = { command = "biome", args = ["format", "--stdin-file-path", "test.json"] }

[[language]]
name = "lua"
auto-format = true
roots = [".luarc.json"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman", "ltex-ls"]
formatter = { command = 'prettierd', args = ["dummy.md"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp", "ruff"]

[[language]]
name = "ruby"
auto-format = true
language-servers = ["standardrb", "solargraph"]

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "biome", args = ["format", "--stdin-file-path", "dummy.ts"] }
language-servers = ["typescript-language-server", "biome"]

[[language]]
name = "yaml"
formatter = { command = 'prettierd', args = ["dummy.yaml"] }
auto-format = true

[language-server.gopls.config]
gofumpt = true
templateExtensions = ["html", "tmpl"]

[language-server.golangci-lint]
command = "golangci-lint-langserver"
config = { command = ["golangci-lint", "run", "--enable-all", "--out-format", "json", "--allow-parallel-runners"] }

[language-server.ltex-ls]
command = "ltex-ls"
config = { ltex = { language = "en-GB" } }

[language-server.lua-language-server]
args = ["--logpath", "$XDG_CACHE_HOME/lua_ls/logs", "--metapath", "$XDG_CACHE_HOME/lua_ls/meta"]

[language-server.lua-language-server.config.Lua.format.defaultConfig]
align_continuous_rect_table_field = "false"
align_array_table = "false"

[language-server.pylsp.config.pylsp]
plugins = { pycodestyle = { enabled = false }, pydocstyle = { enabled = false } } # these two are overriden by ruff

[language-server.biome]
command = "biome"
args = ["lsp-proxy"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.solargraph]
config = { solargraph = { diagnostics = true }, formatting = true }

[language-server.standardrb]
command = "standardrb"
args = ["--lsp"]
