[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
formatter = { command = 'shfmt', args = ["-i", "4", "-p"] }
auto-format = true

[[language]]
name = "css"
formatter = { command = 'prettierd', args = ["dummy.css"] }

[[language]]
name = "scss"
formatter = { command = 'prettierd', args = ["dummy.scss"] }

[[language]]
name = "fish"
formatter = { command = "fish_indent" }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "golangci-lint"]

[[language]]
name = "html"
formatter = { command = 'prettierd', args = ["dummy.html"] }

[[language]]
name = "javascript"
auto-format = true
language-servers = ["typescript-language-server", "rome"]
formatter = { command = "rome", args = ["format", "--stdin-file-path", "test.js"] }

[[language]]
name = "json"
auto-format = true
language-servers = ["json-ls", "rome"]
formatter = { command = "rome", args = ["format", "--stdin-file-path", "test.json"] }

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
auto-format = true
language-servers = ["marksman", "ltex-ls"]
formatter = { command = 'prettierd', args = ["dummy.md"] }

[[language]]
name = "python"
auto-format = true
language-servers = ["pylsp", "ruff"]

[[language]]
name = "ruby"
auto-format = true
language-servers = ["standardrb", "solargraph"]

[[language]]
name = "rust"
formatter = { command = "cargo", args = ["clippy", "--fix", "--allow-dirty", "--allow-staged"] }

[[language]]
name = "toml"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "rome", args = ["format", "--stdin-file-path", "dummy.ts"] }
language-servers = ["typescript-language-server", "rome"]

[[language]]
name = "yaml"
formatter = { command = 'prettierd', args = ["dummy.yaml"] }
auto-format = true

[language-server.gopls]
config = { gopls = { gofumpt = true } }

[language-server.golangci-lint]
command = "golangci-lint-langserver"
config = { command = ["golangci-lint", "run", "--enable-all", "--out-format", "json", "--issues-exit-code=1"] }

[language-server.ltex-ls]
command = "ltex-ls"
config = { ltex = { language = "en-GB" } }

[language-server.lua-language-server]
args = ["--logpath", "$XDG_CACHE_HOME/lua_ls/logs", "--metapath", "$XDG_CACHE_HOME/lua_ls/meta"]

[language-server.lua-language-server.config.Lua.format.defaultConfig]
align_continuous_rect_table_field = "false"
align_array_table = "false"

[language-server.pylsp.config.pylsp]
plugins = { pycodestyle = { enabled = false }, pydocstyle = { enabled = false } } # these two are overriden by ruff

[language-server.rome]
command = "rome"
args = ["lsp-proxy"]

[language-server.ruff]
command = "ruff-lsp"

[language-server.solargraph]
config = { solargraph = { diagnostics = true }, formatting = true }

[language-server.standardrb]
command = "standardrb"
args = ["--lsp"]
