[[language]]
name = "ruby"
auto-format = true
formatter = { command = "rubocop", args = [
  "--autocorrect",
  "--stdin",
  "dummy.rb",
  "--stderr",
  "--fail-level",
  "fatal",
] }
language-servers = ["solargraph"]
