#!/usr/bin/env python
import os
import sys


def has_gemfile(workdir: str) -> bool:
    if os.path.exists(os.path.join(workdir, "Gemfile")):
        return True

    if workdir not in ["/", os.environ["HOME"]]:
        return has_gemfile(os.path.dirname(workdir))

    return False


dir = os.getcwd()
for n, i in enumerate(sys.argv[1:], start=1):
    if os.path.exists(i):
        sys.argv[n] = os.path.abspath(i)
        dir = os.path.dirname(sys.argv[n])

os.chdir(dir)

if has_gemfile(dir):
    os.execvp("bundle", ["bundle", "exec", "rubocop"] + sys.argv[1:])
else:
    os.execvp(
        "rubocop",
        [os.path.join(os.environ["XDG_DATA_HOME"], "asdf", "shims", "rubocop")]
        + sys.argv[1:],
    )
