#!/usr/bin/env python
import os
import subprocess
import sys

dir = os.getcwd()
for n, i in enumerate(sys.argv[1:], start=1):
    if os.path.exists(i):
        sys.argv[n] = os.path.abspath(i)
        dir = os.path.dirname(sys.argv[n])

os.chdir(dir)

if subprocess.call("bundle env 2>/dev/null | grep -q Gemfile", shell=True) == 0:
    os.execvp("bundle", ["bundle", "exec", "rubocop"] + sys.argv[1:])
else:
    os.execvp("rubocop", ["rubocop"] + sys.argv[1:])
