set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viewdir=$XDG_CACHE_HOME/vim/views
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

if empty(glob($XDG_CONFIG_HOME . '/vim/autoload/plug.vim'))
  silent !curl -fLo $XDG_CONFIG_HOME/vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" {{{
call plug#begin()
  Plug 'airblade/vim-gitgutter'
  Plug 'benjamineskola/vim-applescript'
  Plug 'chriskempson/base16-vim'
  Plug 'christoomey/vim-sort-motion' | Plug 'kana/vim-textobj-indent'
  Plug 'ervandew/supertab'
  Plug 'mileszs/ack.vim'
  Plug 'nelstrom/vim-textobj-rubyblock' | Plug 'kana/vim-textobj-user'
  Plug 'neomake/neomake'
  Plug 'Raimondi/delimitMate'
  Plug 'sheerun/vim-polyglot'
  Plug 'sjl/gundo.vim'
  Plug 'sjl/splice.vim'
  Plug 'tpope/vim-commentary'
  Plug 'tpope/vim-endwise'
  Plug 'tpope/vim-eunuch'
  Plug 'tpope/vim-repeat'
  Plug 'tpope/vim-surround'
  Plug 'tpope/vim-unimpaired'
  Plug 'vim-airline/vim-airline'
  Plug 'w0rp/ale'
  Plug 'Yggdroot/indentLine'
  Plug 'Yggdroot/LeaderF', { 'do': './install.sh' }
call plug#end()
" }}}

set autoindent
set autoread
set backspace=indent,eol,start
set encoding=utf-8
set foldmethod=marker
set formatoptions+=j
set guifont=Fira\ Code:h14
set hidden
set history=10000
set hlsearch incsearch
set ignorecase smartcase
set laststatus=2
set mouse+=a
set nofsync
set nomodeline
set nrformats-=octal
set number relativenumber
set pastetoggle=<F10>
set scrolloff=5
set shell=/bin/bash
set showcmd
set ttimeout ttimeoutlen=50
set viewoptions=folds
set wildmenu

set grepprg=rg\ --vimgrep\ $*
set grepformat=%f:%l:%c:%m

" appearance.
set termguicolors
let base16colorspace=256
colo base16-materia
syntax on

" filetype stuff.
filetype plugin indent on
let g:is_posix = 1 " /bin/sh is always POSIX, because what the fuck.

au FileType applescript,javascript,sh,vim,zsh set sts=2 sw=2 expandtab
au FileType fish,haskell set sts=4 sw=4 expandtab

au BufNewFile,BufRead .Brewfile set filetype=ruby
au BufNewFile,BufRead .config/git/config set filetype=gitconfig

" plugin settings
let g:ackprg = 'rg --vimgrep --hidden'

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
let g:airline#extensions#tabline#tab_nr_type = 2
let g:airline_powerline_fonts = 1

let g:ale_fix_on_save = 1
let g:ale_fixers = {
  \ '*': ['remove_trailing_lines', 'trim_whitespace'],
  \ 'bash': ['shfmt'],
  \ 'fish': [{buffer -> { 'command': 'fish_indent' }}],
  \ 'ruby': ['rubocop'],
  \ 'sh': ['shfmt'],
\ }
let g:ale_linters_explicit = 1
let g:ale_set_highlights = 0
au FileType sh let b:sh_shfmt_options = '-p'

let g:delimitMate_expand_cr = 1
let g:delimitMate_expand_space = 1

let g:Lf_CacheDirectory = $XDG_CACHE_HOME
let g:Lf_CommandMap = {'<C-T>': ['<CR>']}

let g:indentLine_char = '⎸'

let g:python_host_prog = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'

call neomake#configure#automake('nrwi', 500)
autocmd! BufReadPost,BufWritePost,BufWinEnter * Neomake
let g:neomake_open_list = 2
let g:neomake_python_exe = '/usr/local/bin/python3'

let g:sort_motion_flags = "i"

" mappings
let mapleader = ","

nmap <C-l> :nohl<CR>:redraw<CR>

let g:nremap = {"]t": "", "[t": ""}
map ]t gt
map [t gT

nnoremap <F5> :GundoToggle<CR>

imap § <ESC>

cnoreabbrev Ack Ack!
nnoremap <Leader>a :Ack!<Space>

map Q gq

" miscellaneous

let $BASH_ENV = $XDG_CONFIG_HOME . "/bash_profile"
autocmd BufEnter * if &buftype == 'help' && &columns > 120 && &columns == winwidth(0) | wincmd L | endif
