require: standard

inherit_gem:
  standard:
    - config/base.yml

Naming/FileName:
  Exclude:
    - "**/*Brewfile*"

Layout/LineLength:
  Enabled: true
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodParameterLineBreaks:
  Enabled: true
