require: standard

inherit_gem:
  standard:
    - config/base.yml

Naming/FileName:
  Exclude:
    - "**/*Brewfile*"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
