- name: Link preferences into place
  file:
    src: '{{ lookup("env", "XDG_CONFIG_HOME", default=lookup("env", "HOME") + "/.config") }}/{{ item.name }}'
    dest: '{{ lookup("env", "HOME") }}/Library/Preferences/{{ item.name }}'
    state: link
  loop:
    - { name: espanso }
    - { name: rustfmt }
