- name: Ensure dotfiles and scripts are up to date
  command:
    cmd: git pull --rebase -q
    chdir: '{{ item }}'
  loop:
    - '{{ config_dir }}'
    - '{{ home }}/bin'

- name: Link preferences into place
  file:
    src: '{{ config_dir }}/{{ item }}'
    dest: '{{ home }}/Library/Preferences/{{ item }}'
    state: link
  loop:
    - espanso
    - rustfmt

- name: Create iTerm2 script directory
  file:
    dest: '{{ data_dir }}/Application Support/iTerm2/Scripts'
    state: directory
- name: Link iTerm2 scripts into place
  copy:
    src: '{{ item }}'
    dest: '{{ data_dir }}/Application Support/iTerm2/Scripts'
  with_fileglob:
    - '{{ config_dir }}/scripts/iterm*'

- name: Check age of iTerm2 integration
  find:
    paths:
      - '{{ config_dir }}/fish/conf.d'
    pattern: zzz_iterm2_shell_integration.fish
    age: -7d
  register: iterm2_integration

- name: Install iTerm2 integration
  get_url:
    url: https://iterm2.com/shell_integration/fish
    dest: '{{ config_dir }}/fish/conf.d/zzz_iterm2_shell_integration.fish'
  when: iterm2_integration.matched == 0

- name: Install dotfiles
  file:
    src: '{{ item }}'
    dest: '{{ home }}/{{ item | basename | regex_replace("^_", ".") }}'
  with_fileglob:
    - '{{ config_dir }}/_*'
    - '{{ config_dir }}/private/_*'

- name: Clean up old dotfile links
  command: find -L "$HOME" -type l -maxdepth 1 -name '.*' -exec rm {} +
