- name: Ensure .gem points to the right place
  file:
    src: '{{ data_dir }}/gem'
    dest: '{{ home }}/.gem'
    state: link

- name: Ensure default XDG paths are symlinked
  block:
    - file:
        dest: '{{ home }}/.local'
        state: directory
    - file:
        src: '{{ home }}/Library'
        dest: '{{ home }}/.local/{{ item.name }}'
        state: link
      loop:
        - { name: share }
        - { name: state }
