- name: Ensure dotfiles and scripts are up to date
  command:
    cmd: git pull --rebase -q
    chdir: '{{ item }}'
  loop:
    - '{{ ansible_env.XDG_CONFIG_HOME }}'
    - '{{ ansible_env.HOME }}/bin'

- name: Link preferences into place
  file:
    src: '{{ ansible_env.XDG_CONFIG_HOME }}/{{ item }}'
    dest: '{{ ansible_env.HOME }}/Library/Preferences/{{ item }}'
    state: link
  loop:
    - espanso
    - rustfmt

- name: Create iTerm2 script directory
  file:
    dest: '{{ ansible_env.XDG_DATA_HOME }}/Application Support/iTerm2/Scripts'
    state: directory
- name: Link iTerm2 scripts into place
  copy:
    src: '{{ item }}'
    dest: '{{ ansible_env.XDG_DATA_HOME }}/Application Support/iTerm2/Scripts'
  with_fileglob:
    - '{{ ansible_env.XDG_CONFIG_HOME }}/scripts/iterm*'

- name: Check age of iTerm2 integration
  find:
    paths:
      - '{{ ansible_env.XDG_CONFIG_HOME }}/fish/conf.d'
    pattern: zzz_iterm2_shell_integration.fish
    age: -7d
  register: iterm2_integration

- name: Install iTerm2 integration
  get_url:
    url: https://iterm2.com/shell_integration/fish
    dest: '{{ ansible_env.XDG_CONFIG_HOME }}/fish/conf.d/zzz_iterm2_shell_integration.fish'
  when: iterm2_integration.matched == 0

- name: Install dotfiles
  file:
    src: '{{ item }}'
    dest: '{{ ansible_env.HOME }}/{{ item | basename | regex_replace("^_", ".") }}'
  with_fileglob:
    - '{{ ansible_env.XDG_CONFIG_HOME }}/_*'
    - '{{ ansible_env.XDG_CONFIG_HOME }}/private/_*'

- name: Clean up old dotfile links
  command: find -L "$HOME" -type l -maxdepth 1 -name '.*' -exec rm {} +

- name: Install plists
  template:
    src: '{{ item }}'
    dest: '{{ ansible_env.XDG_DATA_HOME }}/LaunchAgents/{{ item | basename }}'
  with_fileglob:
    - '{{ ansible_env.XDG_CONFIG_HOME }}/LaunchAgents/*.plist'
  vars:
    env:
      - PATH
      - XDG_CACHE_HOME
      - XDG_CONFIG_HOME
      - XDG_DATA_HOME

- name: Run plists
  community.general.launchd:
    name: '{{ item | basename | regex_replace("\.plist$", "") }}'
    state: started
  with_fileglob:
    - '{{ ansible_env.XDG_CONFIG_HOME }}/LaunchAgents/*.plist'

- name: Clean up old plists
  shell: |
    for i in "$HOME/Library/LaunchAgents/"uk.eskola.*.plist; do
        if ! [ -f "$XDG_CONFIG_HOME/LaunchAgents/$(basename "$i")" ]; then
            launchctl unload "$i"
            rm "$i"
        fi
    done
