---
- name: Don't automatically rearrange spaces
  command: defaults write com.apple.dock mru-spaces -bool false
  changed_when: true
- name: Set up homebrew
  when: ansible_hostname == "Macbook-Pro"
  block:
    - name: Check Homebrew recency
      find:
        paths: [/opt/homebrew/.git]
        age: -24h
        recurse: true
      register: homebrew_files

    - name: Run Homebrew role
      when: homebrew_files.matched == 0
      include_role:
        name: geerlingguy.mac.homebrew
