- name: Make iterm config behave
  block:
    - command: 'defaults write com.googlecode.iterm2 DynamicProfilesPath "{{ ansible_env.XDG_CONFIG_HOME }}/iterm2"'
    - command: 'defaults write com.googlecode.iterm2 PreferredBaseDir "{{ ansible_env.XDG_CACHE_HOME }}/iTerm2"'

- name: Don't automatically rearrange spaces
  command: defaults write com.apple.dock mru-spaces -bool false
