---
- name: Ensure Bat theme directory exists
  file:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/bat/themes"
    state: directory
    mode: "0700"

- name: Vim files newer than a day old
  find:
    paths: ["{{ ansible_env.XDG_DATA_HOME }}/nvim/lazy"]
    age: -24h
    recurse: true
  register: nvim_pack
- name: Ensure neovim packages are up to date
  command: |
    nvim --headless -c 'lua require("lazy").sync()' -c 'qall'
  when: nvim_pack.matched == 0
  changed_when: true

- name: Ensure python-lsp has additional dependencies
  shell:
    cmd: |
      set -e
      . venv/bin/activate
      pip install -U --disable-pip-version-check python-lsp-black pyls-isort pylsp-mypy
    chdir: "{{ ansible_env.XDG_DATA_HOME }}/nvim/mason/packages/python-lsp-server"
  when: nvim_pack.matched == 0
  register: python_lsp
  changed_when: '"Successfully installed" in python_lsp.stdout'

- name: Hammerspoon spoons
  block:
    - name: Core # noqa latest[git]
      git:
        repo: https://github.com/Hammerspoon/Spoons.git
        dest: "{{ ansible_env.XDG_CONFIG_HOME }}/_hammerspoon/Spoons/vendor"
        depth: 1
    - name: Bear # noqa latest[git]
      git:
        repo: https://github.com/dcreemer/hammerspoon-bear.git
        dest: "{{ ansible_env.XDG_CONFIG_HOME }}/_hammerspoon/Spoons/Bear.spoon"
        depth: 1

- name: Install golangci-lint language server
  command:
    cmd: go install github.com/nametake/golangci-lint-langserver@latest
    creates: "{{ ansible_env.XDG_DATA_HOME }}/go/bin/golangci-lint-langserver"
