- name: Install Python versions
  environment:
    PYENV_ROOT: "{{ ansible_env.XDG_DATA_HOME }}/pythons"
  block:
    - name: Get available minor versions
      shell: 'python-build --definitions | grep "^3" | grep -v "[a-z]" | cut -d . -f 1-2 | sort -u --version-sort | tail -n +8'
      register: python_minor_versions
    - name: Get patch version for each minor version
      shell: 'python-build --definitions | grep "^{{ item }}\." | tail -n 1'
      with_items: "{{ python_minor_versions.stdout_lines }}"
      register: python_versions
    - name: Install latest patch version for each minor version
      shell:
        cmd: |
          pyenv install -s {{ item }}
          eval "$(pyenv init -)"
          pyenv shell {{ item }}
          pyenv exec pip install --upgrade pip
          pyenv exec pip install -r {{ ansible_env.XDG_CONFIG_HOME }}/requirements.txt
        creates: "{{ ansible_env.XDG_DATA_HOME }}/pythons/versions/{{ item }}"
      with_items: '{{ python_versions.results | map(attribute="stdout_lines") }}'
      register: python_install
    - debug:
        msg: '{{ (python_versions.results | last)["changed"] }}'
    - name: Set newest version as default
      command: 'pyenv global {{ python_versions.results | map(attribute="stdout_lines") | last | first }}'
      changed_when: python_install.results | last is changed
    - name: Install additional dependencies for non-virtualenv projects
      shell: |
        eval "$(pyenv init -)"
        for req in ~/Code/*/requirements*.txt ~/Code/Personal/*/requirements*.txt; do
          test -f "$req" || continue
          proj="$(dirname "$req")"
          test -e "$proj/.venv" && continue
          echo "$proj" >&2
          pip install -r "$req"
        done
