---
- name: Ensure .gem points to the right place
  file:
    src: "{{ ansible_env.XDG_DATA_HOME }}/gem"
    dest: "{{ ansible_env.HOME }}/.gem"
    state: link

- name: Install Ruby versions
  vars:
    rubies_dir: "{{ ansible_env.XDG_DATA_HOME }}/rubies"
  environment:
    RUBIES_DIR: "{{ rubies_dir }}"
  block:
    - name: Get available stable versions
      shell: ruby-install --update | sed -n -E '/^[^a-z]+$/,${/[0-9]/{s/ //g;p;}; /[a-z]/q; }' | grep -v '^2\.6\.'
      register: ruby_versions
      changed_when: false
    - name: Install stable versions
      shell:
        cmd: |
          if brew --prefix capstone 2>/dev/null; then
            export CXXFLAGS="-I$(brew --prefix capstone)/include"
            export LDFLAGS="-L$(brew --prefix capstone)/lib"
          fi
          RUBY_TMP="$(mktemp -d)"
          ruby-install --no-install-deps --no-reinstall --cleanup -r "$RUBIES_DIR" -s "$RUBY_TMP" "{{ item }}" # -- --enable-shared
        creates: "{{ ansible_env.XDG_DATA_HOME }}/rubies/ruby-{{ item }}"
      with_items: "{{ ruby_versions.stdout_lines }}"
      register: ruby_install
    - name: Set newest version as default
      file:
        src: "{{ rubies_dir }}/ruby-{{ ruby_versions.stdout_lines | last }}"
        dest: "{{ rubies_dir }}/default"
        state: link
      changed_when: ruby_install.results | last is changed
    - name: Find installed ruby versions
      find:
        paths: ["{{ rubies_dir }}"]
        recurse: false
        file_type: directory
        patterns: [ruby-*]
      register: installed_rubies
    - name: Create Gemfile
      template:
        src: templates/Gemfile.j2
        dest: "{{ rubies_dir }}/Gemfile"
        mode: "0600"
      vars:
        gems:
          - bundler
          - mdless
          - pry
          - reek
          - rspec
          - solargraph
          - solargraph-rails
          - standard
    - name: Install required gems
      shell:
        cmd: |
          chruby-exec {{ item }} -- bundle install --gemfile="$RUBIES_DIR/Gemfile"
          rm -f "$RUBIES_DIR/Gemfile.lock"
      with_items: "{{ ruby_versions.stdout_lines }}"
      register: gem_install
      changed_when: "'Installing' in gem_install.stdout"
