---
- name: Ensure .gem points to the right place
  file:
    src: "{{ ansible_env.XDG_DATA_HOME }}/gem"
    dest: "{{ ansible_env.HOME }}/.gem"
    state: link

- name: Install Ruby versions
  environment:
    RUBIES_DIR: "{{ ansible_env.XDG_DATA_HOME }}/rubies"
  block:
    - name: Get available stable versions
      shell: ruby-install --update | sed -n -E '/^[^a-z]+$/,${/[0-9]/{s/ //g;p;}; /[a-z]/q; }' | grep -v '^2\.6\.'
      register: ruby_versions
      changed_when: false
    - name: Install stable versions
      shell:
        cmd: |
          if brew --prefix capstone 2>/dev/null; then
            export CXXFLAGS="-I$(brew --prefix capstone)/include"
            export LDFLAGS="-L$(brew --prefix capstone)/lib"
          fi
          RUBY_TMP="$(mktemp -d)"
          ruby-install --no-reinstall --cleanup -r "$RUBIES_DIR" -s "$RUBY_TMP" "{{ item }}" -- --enable-shared
        creates: "{{ ansible_env.XDG_DATA_HOME }}/rubies/ruby-{{ item }}"
      with_items: "{{ ruby_versions.stdout_lines }}"
      register: ruby_install
    - name: Set newest version as default
      file:
        src: "{{ ansible_env.RUBIES_DIR }}/ruby-{{ ruby_versions.stdout_lines | last }}"
        dest: "{{ ansible_env.RUBIES_DIR }}/default"
        state: link
      changed_when: ruby_install.results | last is changed
    - name: Find installed ruby versions
      find:
        paths: ["{{ ansible_env.RUBIES_DIR }}"]
        recurse: false
        file_type: directory
        patterns: [ruby-*]
      register: installed_rubies
    - name: Install required gems
      shell:
        cmd: |
          test -n "$(chruby-exec {{ item[0] }} -- gem list -q -e '{{ item[1] }}')" || \
            chruby-exec {{ item[0] }} -- gem install '{{ item[1] }}'
      with_nested:
        - "{{ installed_rubies.files | map(attribute='path') | map('basename') | reject('regex', '^ruby-2.6') }}"
        - "{{ gems }}"
      changed_when: '"gem installed" in gem_install.stdout or "gems installed" in gem_install.stdout'
      register: gem_install
      vars:
        gems:
          - bundler
          - erb_lint
          - mdless
          - neovim
          - pry
          - rspec
          - solargraph
          - solargraph-rails
          - standard
