---
- name: Ensure .gem points to the right place
  file:
    src: "{{ ansible_env.XDG_DATA_HOME }}/gem"
    dest: "{{ ansible_env.HOME }}/.gem"
    state: link

- name: Install Ruby versions
  environment:
    RUBIES_DIR: "{{ ansible_env.XDG_DATA_HOME }}/rubies"
  block:
    - name: Get available stable versions
      shell: ruby-install | sed -n -E '/^[^a-z]+$/,${/[0-9]/{s/ //g;p;}; /[a-z]/q; }' | grep -v '^2\.6\.'
      register: ruby_versions
      changed_when: false
    - name: Install stable versions
      shell:
        cmd: |
          if brew --prefix capstone 2>/dev/null; then
            export CXXFLAGS="-I$(brew --prefix capstone)/include"
            export LDFLAGS="-L$(brew --prefix capstone)/lib"
          fi
          ruby-install --no-reinstall --cleanup -r "$RUBIES_DIR" "{{ item }}" -- --enable-shared
          chruby-exec {{ item }} -- xargs gem install < {{ ansible_env.XDG_CONFIG_HOME }}/default-gems.txt || true
        creates: "{{ ansible_env.XDG_DATA_HOME }}/rubies/ruby-{{ item }}"
      with_items: "{{ ruby_versions.stdout_lines }}"
      register: ruby_install
    - name: Set newest version as default
      file:
        src: "{{ ansible_env.XDG_DATA_HOME }}/rubies/ruby-{{ ruby_versions.stdout_lines | last }}"
        dest: "{{ ansible_env.XDG_DATA_HOME }}/rubies/default"
        state: link
      changed_when: ruby_install.results | last is changed
