- name: Ensure .gem points to the right place
  file:
    src: '{{ ansible_env.XDG_DATA_HOME }}/gem'
    dest: '{{ ansible_env.HOME }}/.gem'
    state: link

- name: Ensure default XDG paths are symlinked
  block:
    - file:
        dest: '{{ ansible_env.HOME }}/.local'
        state: directory
    - file:
        src: '{{ ansible_env.HOME }}/Library'
        dest: '{{ ansible_env.HOME }}/.local/{{ item.name }}'
        state: link
      loop:
        - { name: share }
        - { name: state }
