#!/bin/sh
set -e

RE='1s/\.\s*$//'
if sed -v 2>&1 | grep -q GNU; then
  sed -i "$RE" "$1"
else
  sed -i '' "$RE" "$1"
fi

# 50,
#  +1 because no -gte in bourne shell,
#  +1 because wc includes line ending
test 52 -gt "$(head -n 1 "$1" | wc -m)" || {
  echo >&2 "Initial line of commit message too long."
  exit 1
}

tail -n +2 "$1" | sed '/^# -{24} >8 -{24}$/,$d; /^#/d' | while read -r LINE; do
  test 73 -gt "${#LINE}" || {
    echo >&2 "Subsequent line of commit message too long."
    exit 1
  }
done
