#!/usr/bin/env zsh

virtualenv_base=$PWD
while [[ $virtualenv_base != / ]]; do
	if [[ -d $virtualenv_base/.venv ]]; then
		break
	fi
	virtualenv_base="$(dirname "$virtualenv_base")"
done

if [[ $virtualenv_base == / ]]; then
	if which deactivate >/dev/null; then
		echo "deactivating virtualenv $VIRTUAL_ENV"
		deactivate
	fi
	return
fi

if [[ $VIRTUAL_ENV != "$virtualenv_base/.venv" ]]; then
	if which deactivate >/dev/null; then
		echo "deactivating virtualenv"
		deactivate
	fi

	echo "activating virtualenv $virtualenv_base"
	. "$virtualenv_base/.venv/bin/activate"
fi
