#!/usr/bin/env zsh

zparseopts -D -E -- y=yes -yes=yes

rev=$(git rev-parse "$1")
shift

noninteractive_rebase() {
	env GIT_SEQUENCE_EDITOR=cat git rebase -i "$1^" | grep -v '^#'
}

if [[ -z $yes ]]; then
	git show --stat "$rev"
	printf "Fixup? y/N "
	read -r confirm
	if [[ $confirm != y && $confirm != Y ]]; then
		return
	fi
fi

git commit --fixup "$rev" "$@" && noninteractive_rebase "$rev"
