#!/usr/bin/env zsh
ref=$(__git_prompt_git symbolic-ref --quiet HEAD 2>/dev/null)
ret=$?
if [[ $ret != 0 ]]; then
	[[ $ret == 128 ]] && return # no git repo.
	ref=$(__git_prompt_git rev-parse --short HEAD 2>/dev/null) || return
fi
echo "${ref#refs/heads/}"
