#!/usr/bin/env zsh
target="$1"
shift

local params
if [[ "$1" == -* ]]; then
	params="$params $1"
	shift
fi

cmd=$(preferred-command "$@")
if [[ -n "${cmd}" ]]; then
	alias "${target}=${cmd} ${params}"
else
	return 1
fi
