---
- name: Configure macOS workstation
  hosts: local
  vars:
    homebrew_brewfile_dir: "{{ ansible_env.XDG_CONFIG_HOME }}"
    ansible_become_user: '{{ lookup("env", "USER") }}'
  tasks:
    - include_tasks: tasks/macos.yaml # noqa name[missing]
    - include_tasks: tasks/dotfiles.yaml # noqa name[missing]
    - include_tasks: tasks/homebrew.yaml # noqa name[missing]
    - include_tasks: tasks/packages.yaml # noqa name[missing]
    - include_tasks: tasks/python.yaml # noqa name[missing]
    - include_tasks: tasks/ruby.yaml # noqa name[missing]
    - include_tasks: tasks/rust.yaml # noqa name[missing]
    - include_tasks: tasks/node.yaml # noqa name[missing]
