- name: Configure macOS workstation
  hosts: local
  vars:
    homebrew_brewfile_dir: '{{ ansible_env.XDG_CONFIG_HOME }}'
    ansible_become_user: '{{ lookup("env", "USER") }}'
  tasks:
    - include_tasks: tasks/macos.yaml
    - include_tasks: tasks/dotfiles.yaml
    - include_tasks: tasks/homebrew.yaml
    - include_tasks: tasks/packages.yaml
    - include_tasks: tasks/python.yaml
    - include_tasks: tasks/ruby.yaml
    - include_tasks: tasks/rust.yaml
      when: ansible_hostname == 'MacBook-Pro'
