---
- name: Configure macOS workstation
  hosts: local
  vars:
    homebrew_brewfile_dir: "{{ ansible_env.XDG_CONFIG_HOME }}"
    ansible_become_user: '{{ lookup("env", "USER") }}'
    ansible_async_dir: '{{ lookup("env", "XDG_CACHE_HOME") }}/ansible/async'
  tasks:
    - name: Run all tasks
      include_tasks: "{{ task }}"
      with_fileglob: tasks/*.yaml
      loop_control:
        loop_var: task
      when: "'ANSIBLE_TASK' not in ansible_env"
    - name: Run specified task
      include_tasks: tasks/{{ ansible_env.ANSIBLE_TASK }}.yaml
      when: "'ANSIBLE_TASK' in ansible_env"
