#!/bin/sh
set -e

RE='1s/\.\s*$//'
if sed -v 2>&1 | grep -q GNU; then
  sed -i "$RE" "$1"
else
  sed -i '' "$RE" "$1"
fi

FIRST_LINE="$(head -n 1 "$1")"
test 50 -ge ${#FIRST_LINE} || {
  echo >&2 "Initial line of commit message too long (${#FIRST_LINE})."
  exit 1
}

tail -n +2 "$1" | sed -E '/^# -{24} >8 -{24}$/,$d; /^#/d' | while read -r LINE; do
  test 72 -ge "${#LINE}" || {
    echo >&2 "Subsequent line of commit message too long (${#LINE}): $(echo "${LINE}" | cut -c 1-10)..."
    exit 1
  }
done
