OS=$(uname -s)
ARCH=$(uname -p)

export XDG_CONFIG_HOME=$HOME/.config

if [ "$OS" = Darwin ]; then
    eval $(/opt/homebrew/bin/brew shellenv)

    export XDG_DATA_HOME=$HOME/Library
    export XDG_CACHE_HOME=$HOME/Library/Caches
    export XDG_STATE_HOME=$HOME/Library
    export HOMEBREW_BUNDLE_FILE=$XDG_CONFIG_HOME/Brewfile
else
    export XDG_DATA_HOME=$HOME/.local/share
    export XDG_CACHE_HOME=$HOME/.cache
    export XDG_STATE_HOME=$HOME/.local/state
fi

mkdir -p $XDG_CACHE_HOME

export BUNDLE_USER_CACHE="$XDG_CACHE_HOME/bundler"
export BUNDLE_USER_HOME="$XDG_CONFIG_HOME/bundler"

export EDITOR=neovide
export VISUAL="neovide --nofork"
export GIT_EDITOR=nvim

export LESS="-ImRswFX --mouse"
export LESSHISTFILE="$XDG_CACHE_HOME/less_history"
export MANPAGER='col -bx | bat -l man -p'

export CARGO_DIR=$XDG_DATA_HOME/cargo
export GOPATH=$XDG_DATA_HOME/go
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npmrc"
export PYENV_ROOT=$XDG_DATA_HOME/pythons
export RUBIES_DIR=$XDG_DATA_HOME/rubies
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export YARN_PREFIX=$XDG_DATA_HOME/yarn

export ANSIBLE_HOME=$XDG_CONFIG_HOME/ansible
export ANSIBLE_CONFIG=$ANSIBLE_HOME/ansible.cfg

if [ "$OS" = Darwin ]; then
    # Secretive Config
    export SSH_AUTH_SOCK=/Users/ben/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
fi

path=(
    ~/bin
    $CARGO_DIR/bin
    $GOPATH/bin
    $PYENV_ROOT/shims
    $YARN_PREFIX/bin
    $path
)
