# shellcheck shell=ksh
# shellcheck source=/dev/null
source "$(brew --prefix antigen)/share/antigen/antigen.zsh"
antigen use oh-my-zsh
antigen bundle git
antigen bundle bundler
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-syntax-highlighting
antigen apply

alias curl='curl -gkLsS'

alias fdd='fd .'
alias fdg='fd -g'
alias fetch='curl -gkLO'
alias grep=egrep
if whence -p hexyl >/dev/null; then alias hd=hexyl; else alias hd='hexdump -Cvv'; fi
alias less=bat
alias psed='perl -0777 -p -e'
whence -p rg >/dev/null || alias rg='grep -ri'
alias sed='sed -E'
alias tf='tail -F'
alias mdless='mdless --width 72'
alias exa='exa --git -b'

whence -p exa >/dev/null && alias ls=exa
alias ll='ls -l'
alias la='ls -a'
alias lal='ls -la'
alias lsd='ls -d'

alias vi=hx
alias vim=hx
alias nvim=hx
alias neovide=hx

alias listcops='rubocop -fo'
alias openports='lsof -nP -iTCP -sTCP:LISTEN'
alias fontname='fc-scan --format "%{postscriptname}\n"'
alias ruby-install="ruby-install -r '\$RUBIES_DIR -s '\$RUBY_TMP'"

alias dj='python manage.py'
alias djs='dj shell_plus'
alias djrs='dj runserver'
alias djmm='dj makemigrations'
alias djm='dj migrate'
alias djcsu='dj createsuperuser'

alias gfu=git-fixup
alias gl=glgg
alias glgp='glg -p --pretty=medium'
alias gmv='git mv'
alias grsp='grs -p'
alias gswm=gcm
# alias gs='fish_command_not_found gs' # i never want ghostscript

autoload -Uz compinit
compinit

if [[ $OSTYPE == darwin* ]]; then
	fpath+=("$(brew --prefix)/share/zsh/site-functions") # in case this is system zsh not homebrew
fi
autoload -U promptinit
promptinit
prompt pure

eval "$(zoxide init zsh)"

# shellcheck source=/dev/null
source "$(brew --prefix chruby)/share/chruby/chruby.sh"
# shellcheck source=/dev/null
source "$(brew --prefix chruby)/share/chruby/auto.sh"
export RUBIES=("$RUBIES_DIR"/ruby-*)
eval "$(fnm env --use-on-cd --version-file-strategy recursive)"
eval "$(pyenv init -)"

bindkey '^[[1;3C' forward-word
bindkey '^[[1;3D' backward-word
bindkey '^[OA' history-substring-search-up
bindkey '^[OB' history-substring-search-down

setopt SHARE_HISTORY
# shellcheck disable=SC2034
SAVEHIST=999999999

setopt RC_EXPAND_PARAM
fpath+=("$XDG_CONFIG_HOME/zsh/functions.zwc")
# shellcheck disable=SC2296,SC2086
autoload -U ${fpath%.zwc}/*(.N:t)
zrecompile -p "$XDG_CONFIG_HOME/zsh/functions.zwc" "$XDG_CONFIG_HOME"/zsh/functions/*

autoload -U add-zsh-hook
add-zsh-hook chpwd _virtualenv_autoload
add-zsh-hook precmd _dotenv_load

export FZF_DEFAULT_OPTS='--cycle --layout=reverse --border --height=90% --preview-window=wrap'
export _ZO_FZF_OPTS="$FZF_DEFAULT_OPTS --preview=\"echo '\'{}\'' | cut -f 2 | xargs exa -l\""
. "$(brew --prefix fzf)/shell/key-bindings.zsh"

zle -N _fzf_cd_widget
zle -N _fzf_find_file_widget

bindkey '\ec' _fzf_cd_widget
bindkey '\eo' _fzf_find_file_widget
