[colors]
ansi = [
  '#191919',
  '#fc618d',
  '#7bd88f',
  '#fd9353',
  '#948ae3',
  '#fc618d',
  '#5ad4e6',
  '#bab6c0',
]
background = '#222222'
brights = [
  '#525053',
  '#fc618d',
  '#7bd88f',
  '#fce566',
  '#948ae3',
  '#fc618d',
  '#5ad4e6',
  '#f7f1ff',
]
cursor_bg = '#f6f7ec'
cursor_border = '#f6f7ec'
cursor_fg = '#bab6c0'
foreground = '#bab6c0'
selection_bg = '#363537'
selection_fg = '#bab6c0'

[colors.indexed]

[metadata]
name = 'Monokai Spectrum'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
